#!/bin/bash
#Check localization of Zzz File Manager:r:
if [ ! -f ~/.config/zzzfm/zzzfm_already_localized ]; then zzzfmlocalize ; fi

xrandr --output Virtual1 --mode 1920x1080
VBoxClient --clipboard
copyq
