#!/bin/bash
#Check localization of Zzz File Manager:r:
if [ ! -f ~/.config/zzzfm/zzzfm_already_localized ]; then zzzfmlocalize ; fi

compton -b
xrandr --output Virtual1 --mode 2560x1323
VBoxClient --clipboard
copyq
nitrogen --restore
conkywonky
