- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: update repo and upgrade
      tags: always
      package:
        update_cache: yes
        name: "*"
        state: latest

- hosts: localhost
  vars:
    flavor: "{{ media_info.stdout.split()|first }}"
  tasks:
    - command: cat /var/log/installer/media-info
      register: media_info
    - debug:
        var: flavor

- hosts: localhost
  connection: local
  tags: base
  become: true
  roles:
    - base

- hosts: localhost
  connection: local
  tags: fedora,debian,lubuntu
  become: true
  roles:
    - role: fedora
      when: ansible_distribution == "Fedora"
    - role: debian
      when: ansible_distribution == "Debian"
    - role: lubuntu
      when: flavor == "Lubuntu"
