- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: update repo and upgrade
      tags: always
      package:
        update_cache: yes
        name: "*"
        state: latest

  name: get flavor
  # vars:
  #   flavor: "{{ media_info.stdout.split()|first }}"
  tasks:
    - shell:
        cmd: cat /var/log/installer/media-info | awk '{print $1}'
      register: flavor
    # - debug:
    #     msg="{{ cat /var/log/installer/media-info | awk '{print $1}' }}"
    #     msg= {{flavor.stdout}}


- hosts: localhost
  connection: local
  tags: base
  become: true
  roles:
    - base

- hosts: localhost
  connection: local
  tags: fedora,debian,lubuntu
  become: true
  roles:
    - role: fedora
      when: ansible_distribution == "Fedora"
    - role: debian
      when: ansible_distribution == "Debian"
    - role: lubuntu
      when: flavor == "Lubuntu"
