- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: update repo and upgrade
      tags: always
      package:
        update_cache: yes
        name: "*"
        state: latest

  name: get flavor
  tasks:
    - shell:
        cmd: cat /var/log/installer/media-info | awk '{print $1}'
      register: flavor
      args:
        executable: /bin/bash
    - debug:
        msg={{flavor.stdout}}

- hosts: localhost
  connection: local
  tags: base
  become: true
  roles:
    - role: base
      when: ansible_distribution != "Void" or ansible_distribution != "Ubuntu"

- hosts: localhost
  connection: local
  tags: fedora,debian,lubuntu,void
  become: true
  roles:
    - role: fedora
      when: ansible_distribution == "Fedora"
    - role: debian
      when: ansible_distribution == "Debian"
    - role: lubuntu
      when: flavor.stdout == "Lubuntu"
    - role: void
      when: ansible_distribution == "Void"
    - role: ubuntu
      when: ansible_distribution == "Ubuntu"
