- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: update repo and upgrade
      tags: always
      package:
        update_cache: yes
        name: "*"
        state: latest
      when: ansible_distribution != "Archlinux"
    
    - name: update Arch
      tags: arch
      pacman:
        update_cache: yes
        upgrade: yes
      when: ansible_distribution == "Archlinux"

- name: get flavor
  hosts: localhost
  tasks:
    - shell:
        cmd: cat /var/log/installer/media-info | awk '{print $1}'
      register: flavor
      args:
        executable: /bin/bash
    - debug:
        msg={{flavor.stdout}}

# - name: get hostname
#   hosts: localhost
#   tasks:
#     - shell:
#         cmd: hostname
#       register: hostname
#       args:
#         executable: /bin/bash
#     - debug:
#         msg={{hostname.stdout}}

- hosts: localhost
  connection: local
  tags: base
  become: true
  roles:
    - role: base
      # when: hostname.stdout != "cbpp"
      when: ansible_distribution != "Archlinux"

- hosts: localhost
  connection: local
  tags: fedora,debian,lubuntu,void,arch
  become: true
  roles:
    - role: fedora
      when: ansible_distribution == "Fedora"
    - role: cbpp
      when: ansible_hostname == "cbpp"
    - role: antix
      when: ansible_hostname == "antix"
    - role: debian
      when: ansible_distribution == "Debian" and ansible_hostname != "cbpp" and ansible_hostname != "antix"
    - role: lubuntu
      when: flavor.stdout == "Lubuntu"
    - role: puppetmaster
      when: ansible_hostname == "ubuntuserver"
    - role: void
      when: ansible_distribution == "Void"
    - role: ubuntu
      when: ansible_distribution == "Ubuntu" and ansible_hostname != "ubuntuserver"
    - role: arch
      when: ansible_distribution == "Archlinux"
