- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: update repo and upgrade
      tags: always
      package:
        update_cache: yes
        name: "*"
        state: latest
      when: ansible_distribution != "Archlinux"
    
    - name: update Arch
      tags: arch
      pacman:
        update_cache: yes
        upgrade: yes
      when: ansible_distribution == "Archlinux"

  name: get flavor
  tasks:
    - shell:
        cmd: cat /var/log/installer/media-info | awk '{print $1}'
      register: flavor
      args:
        executable: /bin/bash
    - debug:
        msg={{flavor.stdout}}

- hosts: localhost
  connection: local
  tags: base
  become: true
  roles:
    - role: base
      when: not (ansible_distribution != "Void" or ansible_distribution != "Ubuntu")

# - hosts: localhost
#   connection: local
#   vars:
#     user_pass: !vault |
#           $ANSIBLE_VAULT;1.1;AES256
#           65663333356137666137383665616666346433643138663237623435613734306165373531303739
#           6666333133653561643262396338333862373735653534350a336336633733343835326637373131
#           66333935333935396263623837366162396162396136643138313739363435376133336265613833
#           3837336239363561370a316466373762373638363835366131303564636530393166333661613561
#           3464

- hosts: localhost
  connection: local
  tags: fedora,debian,lubuntu,void,arch
  become: true
  roles:
    - role: fedora
      when: ansible_distribution == "Fedora"
    - role: debian
      when: ansible_distribution == "Debian"
    - role: lubuntu
      when: flavor.stdout == "Lubuntu"
    - role: void
      when: ansible_distribution == "Void"
    - role: ubuntu
      when: ansible_distribution == "Ubuntu"
    - role: arch
      when: ansible_distribution == "Archlinux"
