- name: create directories
  tags: directories,theme,icons
  file:
    path: /home/{{ user }}/{{item}}
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0755
  with_items:
      - ".poshthemes"
      - ".config"
      - ".config/QuiteRss"
      - ".config/onedrive"

- name: create user dirs 
  become_user: "{{ user }}"
  shell: 
    cmd: xdg-user-dirs-update
  args:
    executable: /bin/bash
    chdir: /home/{{ user }}
