- name: create discord directory
  tags: discord
  file:
    path: /usr/share/discord
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"

- name: discord
  tags: discord
  unarchive:
    src: https://discord.com/api/download?platform=linux&format=tar.gz
    dest: /usr/share/discord
    remote_src: yes
    owner: "{{ user }}"
    group: "{{ user }}"

- name: install discord shortcut
  tags: discord
  copy:
    src: /usr/share/discord/Discord/discord.desktop
    dest: /usr/share/applications
    owner: root
    group: root

- name: edit discord desktop file -1
  tags: discord
  become: true
  lineinfile:
    path: /usr/share/discord/Discord/discord.desktop
    regexp: '^Exec='
    line: 'Exec=/usr/share/discord/Discord/Discord'

- name: edit discord desktop file -2
  tags: discord
  become: true
  lineinfile:
    path: /usr/share/discord/Discord/discord.desktop
    regexp: '^Icon='
    line: 'Icon=/usr/share/discord/Discord/discord.png'
