- name: download polybar scripts
  tags: polybar
  git:
    repo: https://github.com/polybar/polybar-scripts.git
    dest: /home/{{ user }}/git
    clone: yes
    update: yes

- name: edit polybar script
  tags: polybar
  lineinfile:
    path: /home/{{ user }}/git/polybar-scripts/polybar-scripts/updates-xbps/updates-xbps.sh
    regexp: '^echo "# $updates"'
    line: 'echo "$updates"'

- name: change xbps-updates script to executable
  tags: polybar,xbps
  file:
    path: /home/{{ user }}/git/polybar-scripts/polybar-scripts/updates-xbps/updates-xbps.sh
    mode: +x
