- name: check if i3 config file exists
  tags: i3
  stat:
    path: /home/{{ user }}/.config/i3/config
  register: i3config

- name: back up i3 config file
  tags: i3
  copy:
    src: /home/{{ user }}/.config/i3/config
    dest: /home/{{ user }}/.config/i3/config.bak
  when: i3config.stat.exists

- name: install i3 config file
  tags: i3
  copy:
    src: files/config
    dest: /home/{{ user }}/.config/i3/config
    backup: yes
    owner: "{{ user }}"
    group: "{{ user }}"

- name: check if picom config file exists
  tags: picom
  stat:
    path: /home/{{ user }}/.config/picom/picom.conf
  register: picomconfig

- name: back up picom.conf file
  tags: picom,i3
  copy:
    src: /home/{{ user }}/.config/picom/picom.conf
    dest: /home/{{ user }}/.config/picom/picom.conf.bak
    owner: "{{ user }}"
    group: "{{ user }}"
  when: picomconfig.stat.exists

- name: install picom config file
  tags: picom,i3
  copy:
    src: files/picom.conf
    dest: /home/{{ user }}/.config/picom/picom.conf
    owner: "{{ user }}"
    group: "{{ user }}"
    backup: yes

- name: wallpaper
  copy:
    src: files/i3wm-2560×1440.jpg
    dest: /usr/share/wallpapers/
    owner: "{{ user }}"
    group: "{{ user }}"

- name: install polybar config file
  tags: polybar,i3
  copy:
    src: files/config.ini
    dest: /home/{{ user }}/.config/polybar/
    owner: "{{ user }}"
    group: "{{ user }}"
    backup: yes

- name: install polybar launch file
  tags: polybar,i3
  copy:
    src: files/launch.sh
    dest: /home/{{ user }}/.config/polybar/
    owner: "{{ user }}"
    group: "{{ user }}"
    backup: yes

- name: set polybar script to executable
  tags: polybar
  file:
    path: /home/{{ user }}/.config/polybar/script.sh
    mode: +x

- name: install quiterss config
  tags: quiterss
  copy:
    src: ../files/quiterss.ini
    dest: /home/{{ user }}/.config/quiterss/
    owner: "{{ user }}"
    group: "{{ user }}"
    backup: yes

- name: install rofi config file
  tags: rofi,i3
  copy:
    src: files/config.rasi
    dest: /home/{{ user }}/.config/rofi/config.rasi
    owner: "{{ user }}"
    group: "{{ user }}"
    backup: yes
