# - name: create dbus link 
#   tags: dbus
#   file:
#     src: /etc/sv/dbus
#     dest: /var/service
#     owner: root
#     group: root
#     state: link

- name: create dbus link 
  tags: dbus
  become: true
  shell: ln -s /etc/sv/dbus /var/service
  when: stage=1

- name: back up lightdm.conf file
  tags: lightdm
  become: true
  copy:
    src: /etc/lightdm/lightdm.conf
    dest: /etc/lightdm/lightdm.conf.bak
  when: stage=1

- name: edit lightdm.conf file
  tags: lightdm
  become: true
  lineinfile:
    path: /etc/lightdm/lightdm.conf
    regexp: '^#display-setup-script='
    line: 'display-setup-script=xrandr --output Virtual1 --mode 1920x1080'
  when: stage=1

# - name: create lightdm link 
#   tags: lightdm
#   file:
#     src: /etc/sv/lightdm
#     dest: /var/service
#     owner: root
#     group: root
#     state: link

# - name: create lightdm link 
#   tags: dbus
#   become: true
#   shell: ln -s /etc/sv/lightdm /var/lightdm
