- include_vars: "{{ ansible_distribution }}.yml"


# Void specific tasks
# - block:
#   - include_tasks: tasks/packages.yml
#     when: stage is defined
#   - include_tasks: tasks/lightdm.yml
#     when: stage is defined
#   - include_tasks: directories.yml
#     when: stage is not defined
#   # - include_tasks: tasks/i3config.yml
#   #   when: stage is not defined
#   - include_tasks: ../fedora/tasks/oh-my-posh.yml
#     when: stage is not defined
#   - include_tasks: tasks/zsh-alias.yml
#     when: stage is not defined
#   - include_tasks: ../base/tasks/fonts.yml
#     when: stage is not defined
#   - include_tasks: ../lubuntu/tasks/tilix_config.yml
#     when: stage is not defined
#   # - include_tasks: tasks/samba.yml
#   #   when: stage is not defined
#   - include_tasks: discord.yml
#     when: stage is not defined
#   # - include_tasks: git.yml
#   #   when: stage is not defined
#   - include_tasks: onedrive.yml
#     when: stage is not defined

- block:
  - include_tasks: packages.yml
  - include_tasks: directories.yml
  # - include_tasks: services.yml
  - include_tasks: ../base/tasks/geany.yml
  - include_tasks: ../base/tasks/conky.yml
  - include_tasks: ../base/tasks/fonts.yml
  - include_tasks: ../base/tasks/onedrivegui.yml
  - include_tasks: ../base/tasks/nano.yml
  - include_tasks: ../fedora/tasks/oh-my-posh.yml
  - include_tasks: zsh-alias.yml
  - include_tasks: sddm.yml
  - include_tasks: discord.yml
  - include_tasks: onedrive.yml
  - include_tasks: theme-config.yml
  - include_tasks: ../fedora/tasks/tilix_config.yml
  - include_tasks: virtualbox.yml
