- name: install packages
  tags: base
  when: stage=1
  community.general.xbps:
    name: '{{item}}'
  loop:
      - xorg
      - dbus
      - lightdm
      - lightdm-gtk3-greeter
      - lightdm-gtk-greeter-settings
      - i3
      - i3status
      - xterm
      - dmenu
      - lxappearance
      - nano
      - zsh
      - zsh-syntax-highlighting
      - zsh-autosuggestions
      - tilix
      - htop
      - exa
      - ncdu
      - bat
      - duf
      - firefox
      - pcmanfm
      - notepadqq
      - btop
      - xdg-utils
      - xdg-user-dirs
      - picom
      - unzip
      - curl
      - wget
      - dconf
      - dconf-editor
      - nitrogen
      - polybar
      - rofi
      - onedrive
      - samba
      - smbclient
      - cifs-utils
      - libreoffice
      - chromium
      - vscode

      # - xinit
      # - linux-headers
  #  state: latest

- name: setup script
  tags: lightdm
  when: stage=1
  copy:
    src: files/script.sh
    dest: /home/{{ user }}/
    owner: "{{ user }}"
    group: "{{ user }}"

- name: set setup script to executable
  tags: lightdm
  when: stage=1
  file:
    path: /home/{{ user }}/script.sh
    mode: +x