- name: install packages
  tags: base
  community.general.xbps:
    name: '{{item}}'
  loop:
      #GUI
      - arc-theme
      - arc-icon-theme
      - dbus
      - kde5
      - kde5-baseapps
      - xorg

      #Applications
      - vscode
      - xdg-utils
      - xdg-user-dirs
      - curl
      - wget
      - dconf
      - onedrive
      - linux-headers
      - pulseaudio
      - python3-psutil
      - nano
      - vim
      - eza
      - virtualbox-ose
      - virtualbox-ose-guest
  #  state: latest
