- name: install packages
  tags: base
  community.general.xbps:
    name: '{{item}}'
  loop:
      - zsh
      - zsh-syntax-highlighting
      - zsh-autosuggestions
      - tilix
      - htop
      - conky
      - ncdu
      - bat
      # - onedrive  ## Not available on Arch
      - samba
      - cifs-utils
      - "{{ firefox_package }}"
      - thunderbird
      - "{{ libreoffice_package }}"
      - gnupg
      - geany
      - unzip
      - dconf-editor
      - "{{ chromium_package }}"
      - "{{ ssh_package }}"
      - btop
      - CopyQ
      - "{{ fd_package }}"
      - fzf
      - ripgrep
      - duf
      - vim
      - rsync

      #GUI
      - arc-theme
      - arc-icon-theme
      - dbus
      - kde5
      - kde5-baseapps
      - xorg
      - nano
      - vim

      #Applications
      - vscode
      - xdg-utils
      - xdg-user-dirs
      - curl
      - wget
      - dconf
      - onedrive
      - linux-headers
      - pulseaudio
      - python3-psutil
  #  state: latest
