- name: install packages
  tags: base
  community.general.xbps:
    name: '{{item}}'
  loop:
      - xorg
      - dbus
      - lightdm
      - lightdm-gtk3-greeter
      - lightdm-gtk-greeter-settings
      - i3
      - i3status
      - xterm
      - dmenu
      - lxappearance
      - nano
      - zsh
      - zsh-syntax-highlighting
      - zsh-autosuggestions
      - tilix
      - htop
      - exa
      - ncdu
      - bat
      - onedrive
      - samba
      - smbclient
      - cifs-utils
      - duf
      - firefox
      - pcmanfm
      - libreoffice
      - notepadqq
      - chromium
      - vscode
      - btop
      - xdg-utils
      - xdg-user-dirs
      - picom
      - unzip
      - curl
      - wget
      - linux-headers
      - dconf
      - dconf-editor
      - xinit
  #  state: latest
