- name: install packages
  tags: base
  community.general.xbps:
    name: '{{item}}'
  loop:
      #GUI
      - xorg
      - dbus
      - lightdm
      - lightdm-gtk3-greeter
      - lightdm-gtk-greeter-settings
      - i3
      - i3status
      - dmenu
      - lxappearance
      - arc-theme
      - arc-icon-theme
      - picom
      - nitrogen
      - polybar
      - rofi
      
      #Shell
      - zsh
      - zsh-syntax-highlighting
      - zsh-autosuggestions
      - tilix

      #Utils
      - htop
      - exa
      - ncdu
      - bat
      - duf
      - btop
      - nano

      #Applications
      - firefox
      - thunderbird
      - pcmanfm
      - notepadqq
      - libreoffice
      - chromium
      - vscode
      - quiterss

      - xdg-utils
      - xdg-user-dirs
      - unzip
      - curl
      - wget
      - dconf
      - dconf-editor
      - onedrive
      - samba
      - smbclient
      - cifs-utils
      - nerd-fonts
      - linux-headers
      - pulseaudio
      - gnupg

      # - xinit
  #  state: latest

- name: setup script
  tags: lightdm
  copy:
    src: files/script.sh
    dest: /home/{{ user }}/
    owner: "{{ user }}"
    group: "{{ user }}"

- name: set setup script to executable
  tags: lightdm
  file:
    path: /home/{{ user }}/script.sh
    mode: +x
