- name: install packages
  tags: base
  community.general.xbps:
    name: '{{item}}'
  loop:
      #GUI
      - arc-theme
      - arc-icon-theme
      - dbus
      - kde5
      - kde5-baseapps
      # - lightdm
      # - "{{ lightdmgtkgreeter_package }}"
      # - lightdm-gtk-greeter-settings
      - xorg
      # - i3
      # - i3status
      # - dmenu
      # - lxappearance
      # - picom
      # - nitrogen
      # - polybar
      # - rofi
      
      #Shell
      - zsh
      - zsh-syntax-highlighting
      - zsh-autosuggestions
      - tilix

      #Utils
      - htop
      - exa
      - ncdu
      - bat
      - duf
      - btop
      - nano
      - vim

      #Applications
      - "{{ firefox_package }}"
      - thunderbird
      - "{{ libreoffice_package }}"
      - "{{ chromium_package }}"
      # - "{{ ssh_package }}"
      - vscode
      - quiterss
      - geany
      - conky

      - xdg-utils
      - xdg-user-dirs
      - unzip
      - curl
      - wget
      - dconf
      - dconf-editor
      - onedrive
      - samba
      - smbclient
      - cifs-utils
      - nerd-fonts
      - linux-headers
      - pulseaudio
      - gnupg
      - linux-headers
      - python3-psutil

      # - xinit
  #  state: latest

- name: setup script
  tags: lightdm
  copy:
    src: files/script.sh
    dest: /home/{{ user }}/
    owner: "{{ user }}"
    group: "{{ user }}"

- name: set setup script to executable
  tags: lightdm
  file:
    path: /home/{{ user }}/script.sh
    mode: +x
