- name: copy virtualbox desktop file
  copy:
    src: files/vboxclient.desktop
    dest: /home/{{ user }}/.config/autostart/
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0755

- name: add virtualbox to visudo
  lineinfile:
    path: /etc/sudoers
    insertafter: EOF
    line: matt ALL=NOPASSWD:/usr/bin/VBoxClient-all
    state: present
    validate: /usr/sbin/visudo -cf %s

- name: create virtualbox link
  tags: vbox
  become: true
  shell: ln -s /etc/sv/vboxservice /var/service/

- name: start virtualbox service - clipboard
  tags: vbox
  become: true
  shell: VBoxClient --clipboard

- name: start virtualbox service - vmsvga
  tags: vbox
  become: true
  shell: VBoxClient --vmsvga
