# - name: install appimagelauncher
#   get_url:
#     url: https://github.com/TheAssassin/AppImageLauncher/releases/download/v2.2.0/appimagelauncher-2.2.0-travis995.0f91801.x86_64.rpm
#     dest: /home/{{ user }}/Downloads
#     mode: +x
#     owner: "{{ user }}"
#     group: "{{ user }}"


- name: install appimagelauncher
  dnf:
    name: 'https://github.com/TheAssassin/AppImageLauncher/releases/download/v2.2.0/appimagelauncher-2.2.0-travis995.0f91801.x86_64.rpm'
    state: present
    disable_gpg_check: true
