- name: create audacious directory
  tags: geany
  file:
    path: /home/{{ user }}/.config/audacious
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0755

- name: install audacious files
  unarchive:
    src: files/audacious.tar.gz
    dest: /home/{{ user }}/.config
    owner: "{{ user }}"
    group: "{{ user }}"
