- name: copy betterbird install script
  tags: betterbird
  copy:
    src: files/install-betterbird.sh
    dest: /home/{{ user }}
    owner: "{{ user }}"
    group: "{{ user }}"

- name: set polybar script to executable
  tags: betterbird
  file:
    path: /home/{{ user }}/install-betterbird.sh
    mode: +x

- name: install betterbird
  tags: betterbird
  script: /home/{{ user }}/install-betterbird.sh
  become: true