- name: add docker repo
  command: dnf config-manager addrepo --from-repofile=https://download.docker.com/linux/fedora/docker-ce.repo

- name: install docker
  tags: fedora,base,docker
  dnf:
    name:
      - docker-ce    
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
  when: ansible_distribution == "Fedora"

- name: start and enable docker
  tags: docker
  service:
    name: docker
    state: started
    enabled: yes

