# Fedora specific tasks
- block:
  - include_tasks: packages.yml
  - include_tasks: directories.yml
  - include_tasks: vscodium.yml
  - include_tasks: autostart.yml
  - include_tasks: theme-config.yml
  - include_tasks: mate_config.yml
  - include_tasks: oh-my-posh.yml
  - include_tasks: tilix_config.yml
  - include_tasks: zsh-alias.yml
  - include_tasks: poddr.yml
  - include_tasks: rainlendar.yml
  - include_tasks: audacious.yml
  - include_tasks: docker.yml
  - include_tasks: thunderbird-systray.yml
  - include_tasks: ../arch/tasks/obsidian.yml
  - include_tasks: appimagelauncher.yml
  - include_tasks: betterbird.yml
  - include_tasks: work.yml
    # when: work is defined

