- name: set wallpaper
  become_user: "{{ user }}"
  dconf:
    key: "/org/mate/desktop/background/picture-filename"
    value: "'/usr/share/backgrounds/cosmos/background-1.xml'"

- name: set wallpaper position
  become_user: "{{ user }}"
  dconf:
    key: "/org/mate/desktop/background/picture-options"
    value: "'stretched'"

- name: set login wallpaper
  become_user: "{{ user }}"
  dconf:
    key: "/x/dm/slick-greeter/background"
    value: "'/usr/share/backgrounds/mate/desktop/Float-into-MATE.png'"

- name: set screensaver
  become_user: "{{ user }}"
  dconf:
    key: "/org/mate/screensaver/themes"
    value: "['screensavers-popsquares']"

- name: set screensaver lock
  become_user: "{{ user }}"
  dconf:
    key: "/org/mate/screensaver/lock-enabled"
    value: "false"

- name: set screensaver mode
  become_user: "{{ user }}"
  dconf:
    key: "/org/mate/screensaver/mode"
    value: "'single'"

- name: set font
  become_user: "{{ user }}"
  dconf:
    key: "/org/mate/desktop/interface/font-name"
    value: "'Sans 9'"

- name: set theme
  become_user: "{{ user }}"
  dconf:
    key: "/org/mate/desktop/interface/gtk-theme"
    value: "'Material-Black-Cherry-3.36'"

- name: set icon theme
  become_user: "{{ user }}"
  dconf:
    key: "/org/mate/desktop/interface/icon-theme"
    value: "'Delft-Blue-Darkest'"

- name: set window theme
  become_user: "{{ user }}"
  dconf:
    key: "/org/mate/marco/general/theme"
    value: "'DustBlue'"

- name: set top panel backgound color
  become_user: "{{ user }}"
  dconf:
    key: "/org/mate/panel/toplevels/top/background/color"
    value: "'rgba(255,255,255,0)'"

- name: set top panel color
  become_user: "{{ user }}"
  dconf:
    key: "/org/mate/panel/toplevels/top/background/type"
    value: "'color'"

- name: set top panel to bottom
  become_user: "{{ user }}"
  dconf:
    key: "/org/mate/panel/toplevels/top/orientation"
    value: "'bottom'"

- name: set top panel size
  become_user: "{{ user }}"
  dconf:
    key: "/org/mate/panel/toplevels/top/size"
    value: 22

- name: set bottom panel to empty
  become_user: "{{ user }}"
  dconf:
    key: "/org/mate/panel/general/object-id-list"
    value: "['menu-bar', 'file-browser', 'terminal', 'web-browser', 'email-client', 'volume-control', 'notification-area', 'clock']"

- name: remove bottom panel
  become_user: "{{ user }}"
  dconf:
    key: "/org/mate/panel/general/toplevel-id-list"
    value: "['top']"

- name: set laptop lid action-AC
  become_user: "{{ user }}"
  dconf:
    key: "/org/mate/power-manager/button-lid-ac"
    value: "'nothing'"

- name: set laptop lid action-battery
  become_user: "{{ user }}"
  dconf:
    key: "/org/mate/power-manager/button-lid-battery"
    value: "'nothing'"

- name: set inactivity time
  become_user: "{{ user }}"
  dconf:
    key: "/org/mate/desktop/session/idle-delay"
    value: 35

- name: set sleep time-battery
  become_user: "{{ user }}"
  dconf:
    key: "/org/mate/power-manager/sleep-computer-battery"
    value: 600
