- name: install rainlendar
  tags: rainlendar
  unarchive:
    src: https://www.rainlendar.net/download/2.18.0/Rainlendar-Pro-2.18.0-amd64.tar.bz2
    dest: /home/{{ user }}
    remote_src: yes
    owner: "{{ user }}"
    group: "{{ user }}"

- name: install rainlendar license
  tags: rainlendar
  copy:
    src: ../base/files/license.r2lic
    dest: /home/{{ user }}/rainlendar2
    owner: "{{ user }}"
    group: "{{ user }}"
