- name: add vscodium GPG key
  tags: vscodium
  become: true
  shell:
    cmd: sudo rpmkeys --import https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/-/raw/master/pub.gpg
  args:
    executable: /bin/bash

- name: add vscodium repository
  tags: vscodium
  shell:
    cmd: printf "[gitlab.com_paulcarroty_vscodium_repo]\nname=download.vscodium.com\nbaseurl=https://download.vscodium.com/rpms/\nenabled=1\ngpgcheck=1\nrepo_gpgcheck=1\ngpgkey=https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/-/raw/master/pub.gpg\nmetadata_expire=1h" | sudo tee -a /etc/yum.repos.d/vscodium.repo
  args:
    executable: /bin/bash

- name: install vscodium
  tags: vscodium
  become: true
  dnf:
    name:
      - codium
    state: latest
