- name: create directory
  tags: font,fonts
  file:
    path: /home/"{{ user }}"/.local/share/fonts
    state: directory
    mode: '0755'

- name: install fonts
  tags: font,fonts
  unarchive:
    src: files/fonts.tar.gz
    dest: /home/"{{ user }}"/.local/share/fonts
    owner: "{{ user }}"
    group: "{{ user }}"

- name: reload font cache
  tags: font
  shell: fc-cache
