- name: download notepadqq
  tags: notepadqq
  git:
    repo: https://github.com/notepadqq/notepadqq.git
    dest: /home/{{ user }}/notepadqq
    clone: yes
    update: yes

- name: configure notepadqq install
  tags: notepadqq
  shell:
    cmd: ./configure --prefix /usr
    chdir: /home/{{ user }}/notepadqq
  args:
    executable: /bin/bash

- name: make notepadqq
  tags: notepadqq
  make:
    chdir: /home/{{ user }}/notepadqq

- name: make install notepadqq
  tags: notepadqq
  make:
    chdir: /home/{{ user }}/notepadqq
    target: install
