- name: download notepadqq
  tags: notepadqq
  git:
    repo: https://github.com/notepadqq/
    dest: /home/{{ user }}/notepadqq
    clone: yes
    update: yes

- name: configure notepadqq install
  tags: notepadqq
  shell: ./configure --prefix /usr
    args:
    chdir: /home/{{ user }}/notepadqq

- name: make notepadqq
  tags: notepadqq
  make:
    chdir: /home/{{ user }}/notepadqq

- name: make install notepadqq
  tags: notepadqq
  make:
    chdir: /home/{{ user }}/notepadqq
    target: install
