- name: install packages
  tags: base
  dnf:
    name:
      - zsh
      - zsh-syntax-highlighting
      - zsh-autosuggestions
      - tilix
      - duf
      - pidgin
      - cairo-dock
      - htop
      - conky
      - exa
      - ncdu
      - bat
      - onedrive
      - python3-pip
      - samba
      - git
