- name: back up samba config file
  tags: samba
  copy:
    src: /etc/samba/smb.conf
    dest: /etc/samba/smb.conf.bak

#- name: add samba share
#  tags: samba
#  udm_share:
#    name: Downloads
#    path: /home/{{ user }}/Downloads
#    sambaName: Downloads
#    sambaPublic: yes
#    sambaForceCreateMode: yes
#    sambaCreateMode: 0664

- name: add samba share to config file
  tags: samba
  blockinfile:
    path: /etc/samba/smb.conf
    block: |
      [Downloads]
      comment = Downloads Share
      path = /home/{{ user }}/Downloads
      writeable = yes
      browsable = yes
      public = yes
      create mask = 0644
      force create mode = 0644
      directory mask = 0775
      force directory mode = 0775
      write list = user

- name: semanage command
  tags: samba
#  command:
#    cmd: 'semanage fcontext --add --type "samba_share_t" "/home/{{ user }}/Downloads(/.*)?" 2> /dev/null'
  shell: semanage fcontext --add --type "samba_share_t" "/home/{{ user }}/Downloads(/.*)?" 2> /dev/null

- name: restorecon command
  tags: samba
#  command:
#    cmd: 'restorecon -R /home/{{ user }}/Downloads 2> /dev/null'
  shell: restorecon -R /home/{{ user }}/Downloads 2> /dev/null

- name: enable smb
  tags: samba
  service:
    name: smb
    state: started
    enabled: yes

- name: add firewall exception for samba
  tags: samba
  command:
    cmd: firewall-cmd --permanent --add-service="samba"

- name: restart firewall
  tags: samba,firewall
  service:
    name: firewall-cmd
    state: restarted
