- name: autologin - 1
  tags: login
  lineinfile:
    path: /etc/lightdm/lightdm.conf
    regexp: '^#autologin-user='
    line: autologin-user={{ user }}

- name: autologin - 2
  tags: login
  lineinfile:
    path: /etc/lightdm/lightdm.conf
    regexp: '^#autologin-user-timeout=0'
    line: autologin-user-timeout=0
