- name: cleanup package cache
  apt:
    autoclean: yes
  when: ansible_distribution == "Debian" or flavor.stdout == "Lubuntu"

- name: autoremove
  apt:
    autoremove: yes
    purge: yes
  when: ansible_distribution == "Debian" or flavor.stdout == "Lubuntu"

- name: remove install folders
  file:
    path: /home/{{ user }}/{{item}}
    state: absent
  with_items:
    - "notepadqq"
    - "purple-googlechat"
    - "tasks.sh"