- name: copy desktop background
  tags: xfce
  copy:
    src: files/XFCE_X022_FHD_NoLogo.png
    dest: /usr/share/backgrounds/xfce
    owner: "{{ user }}"
    group: "{{ user }}"

- name: install theme
  tags: theme
  unarchive:
    src: files/Blackbird.tar.gz
    dest: /usr/share/themes

- name: install icons
  tags: icons
  unarchive:
    src: files/Gnome-icons.tar.gz
    dest: /usr/share/icons

- name: unzip cairo-dock settings
  tags: cairo-dock
  unarchive:
    src: files/cairo-dock.7z
    dest: /home/{{ user }}/.config/

# - name: download Writer icon
#   copy:
#     src: files/LibreOffice_Writer.png
#     dest: /home/{{ user }}/.config/cairo-dock/current_theme/icons

- name: download settings script
  tags: settings
  copy:
    src: files/tasks.sh
    dest: /home/{{ user }}
    mode: +x
    owner: "{{ user }}"
    group: "{{ user }}"

- name: download tilix settings script
  tags: tilix,settings
  copy:
    src: files/tilix.sh
    dest: /home/{{ user }}
    mode: +x
    owner: "{{ user }}"
    group: "{{ user }}"

- name: add to application autostart
  copy:
    src: files/cairo-dock.desktop
    dest: /home/{{ user }}/.config/autostart
    owner: "{{ user }}"
    group: "{{ user }}"