# - name: add nala to sources list - step 1
#   shell:
#     cmd: echo "deb http://deb.volian.org/volian/ scar main" | sudo tee /etc/apt/sources.list.d/volian-archive-scar-unstable.list
#   args:
#     executable: /bin/bash

# - name: add nala to sources list - step 2
#   tags: nala
#   become: true
#   shell:
#     cmd: wget -qO - https://deb.volian.org/volian/scar.key | sudo tee /etc/apt/trusted.gpg.d/volian-archive-scar-unstable.gpg > /dev/null
# #    chdir: /home/{{ user }}
#   args:
#     executable: /bin/bash
#     # warn: false


- name: check if nala sources already exist
  stat:
    path: /etc/apt/sources.list.d/volian-archive-nala-unstable.sources
  register: nala_exists

- name: download nala sources
  tags: nala
  become: true
  apt:
    deb: "{{ item }}"
  with_items:
    - "https://gitlab.com/volian/volian-archive/uploads/b20bd8237a9b20f5a82f461ed0704ad4/volian-archive-keyring_0.1.0_all.deb"
    - "https://gitlab.com/volian/volian-archive/uploads/d6b3a118de5384a0be2462905f7e4301/volian-archive-nala_0.1.0_all.deb"
  when: not nala_exists


- name: install nala
  tags: nala
  become: true
  package:
    update_cache: yes
    # name: nala-legacy
    name: nala
    state: latest
  when: not nala_exists

- name: add nala to sources list
  shell:
    cmd: echo "deb-src https://deb.volian.org/volian/ scar main" | sudo tee -a /etc/apt/sources.list.d/volian-archive-scar-unstable.list
  args:
    executable: /bin/bash
  when: not nala_exists
