- name: add nala to sources list - step 1
  shell:
    cmd: echo "deb http://deb.volian.org/volian/ scar main" | sudo tee /etc/apt/sources.list.d/volian-archive-scar-unstable.list
  args:
    executable: /bin/bash

- name: add nala to sources list - step 2
  tags: nala
  become: true
  shell:
    cmd: wget -qO - https://deb.volian.org/volian/scar.key | sudo tee /etc/apt/trusted.gpg.d/volian-archive-scar-unstable.gpg > /dev/null
#    chdir: /home/{{ user }}
  args:
    executable: /bin/bash

- name: install nala
  tags: nala
  become: true
  package:
    update_cache: yes
    name: nala-legacy
    state: latest
