- name: add user to sudoers group
  tags: sudoers
  become_user: root
  shell:
    cmd: sudo usermod -aG sudo {{ user }}
  args:
    executable: /bin/bash

- name: add user to visudo
  tags: sudoers
  become_user: root
  shell:
    cmd: echo '{{ user }} ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
