- name: collect uname
  tags: virtualbox
  shell: uname -r
  register: uname_result

- name: install packages for VirtualBox
  tags: virtualbox
  apt:
    name:
      - build-essential
      - dkms
      - linux-headers-{{ uname_result.stdout }}

- name: install VirtualBox Guest Additions
  tags: virtualbox
  shell: bash -c 'sudo sh /media/cdrom0/VBoxLinuxAdditions.run --nox11 2> /dev/null'
#    chdir: /media/cdrom0
#  args:
#    executable: /bin/bash

