- name: add hidden files
  tags: xfconf
  become_user: "{{ user }}"
  xfconf:
    channel: thunar
    property: /last-show-hidden
    value_type: "bool"
    value: "true"

- name: add keyboard shortcut
  tags: xfconf
  xfconf:
    channel: "xfce4-keyboard-shortcuts"
    property: "/commands/custom/<Super>Return"
    value_type: "string"
    value: "/usr/bin/tilix.wrapper"

- name: set background image
  tags: xfconf
  xfconf:
    channel: "xfce4-panel"
    property: "/panels/panel-3/background-image"
    value_type: "string"
    value: "/home/{{ user }}/Pictures/XFCE_X022_FHD_NoLogo.png"

- name: set number of panels
  tags: xfconf
  xfconf:
    channel: "xfce4-panel"
    property: "/panels"
    value_type: "array"
    value: ['3']

