- name: settings
  become_user: "{{ user }}"
  shell:
    cmd: ./tasks.sh
    chdir: /home/{{ user }}
  args:
    executable: /bin/bash


#- name: change background image
#  become_user: "{{ user }}"
#  shell: env DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus xfconf-query --channel xfce4-desktop --property /backdrop/screen0/monitorVirtual1/workspace0/last-image -s /home/matth/Pictures/XFCE_X022_FHD_NoLogo.png
#  args:
#    executable: /bin/bash

#- name: add hidden files
#  become_user: "{{ user }}"
#  shell: env DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus xfconf-query --channel thunar --property /last-show-hidden -s true
#  args:
#    executable: /bin/bash

#- name: add keyboard shortcut
#  become_user: "{{ user }}"
#  shell: env DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus xfconf-query -c xfce4-keyboard-shortcuts -p "/commands/custom/<Super>Return" -n -t string -s /usr/bin/tilix.wrapper
#  args:
#    executable: /bin/bash

#- name: set number of panels
#  become_user: "{{ user }}"
#  shell: env DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus xfconf-query --channel xfce4-panel --property /panels -s ['3']
#  args:
#    executable: /bin/bash


#- name: set workspace names
#  become: true
#  become_user: "{{ user }}"
#  xfconf:
#    channel: xfwm4
#    property: /general/workspace_names
#    value_type: string
#    value: ['Main']
#    force_array: true
#  environment:
#    DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/dbus

#- name: add hidden files
#  tags: xfconf
#  become_user: "{{ user }}"
#  xfconf:
#    channel: thunar
#    property: /last-show-hidden
#    value_type: "bool"
#    value: "true"
#  environment:
#    DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/dbus

#- name: add keyboard shortcut
#  tags: xfconf
#  xfconf:
#    channel: "xfce4-keyboard-shortcuts"
#    property: "/commands/custom/<Super>Return"
#    value_type: "string"
#    value: "/usr/bin/tilix.wrapper"

#- name: set background image
#  tags: xfconf
#  become: true
#  become_user: "{{ user }}"
#  xfconf:
#    channel: xfce4-desktop
#    property: /backdrop/screen0/monitorVirtual1/workspace0/last-image
#    value_type: string
#    value: /home/{{ user }}/Pictures/XFCE_X022_FHD_NoLogo.png
#  environment:
#    DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/dbus

#- name: set number of panels
#  tags: xfconf
#  xfconf:
#    channel: "xfce4-panel"
#    property: "/panels"
#    value_type: "array"
#    value: ['3']
#  environment:
#    DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/dbus

