- name: zsh config file
  tags: zsh
  copy:
    src: files/zshrc
    dest: /home/{{ user }}/.zshrc
    owner: "{{ user }}"
    group: "{{ user }}"

- name: alias file
  tags: alias
  copy:
    src: files/aliasrc
    dest: /home/{{ user }}
    owner: "{{ user }}"
    group: "{{ user }}"

- name: source .zshrc file
  tags: alias,zsh
  shell: bash -c 'source /home/{{ user }}/.zshrc 2> /dev/null'
#  ignore_errors: true

- name: source aliasrc file
  tags: alias,zsh
  shell: bash -c 'source /home/{{ user }}/aliasrc 2> /dev/null'

- name: change shell
  tags: zsh,shell
  shell: usermod --shell /bin/zsh {{ user }}
