#- name: install powerlevel10k
#  tags: zsh
#  unarchive:
#    src: files/powerlevel10k.tar.gz
#    dest: /home/{{ user }}
#    owner: "{{ user }}"
#    group: "{{ user }}"

- name: zsh config file - 1
  tags: zsh
  copy:
    src: files/zshrc
    dest: /home/{{ user }}/.zshrc
    owner: "{{ user }}"
    group: "{{ user }}"

- name: zsh config file - 2
 tags: zsh
 copy:
   src: files/p10k.zsh
   dest: /home/{{ user }}/.p10k.zsh
   owner: "{{ user }}"
   group: "{{ user }}"

- name: alias file
  tags: alias
  copy:
    src: files/aliasrc
    dest: /home/{{ user }}
    owner: "{{ user }}"
    group: "{{ user }}"

- name: change shell
  tags: zsh,shell
  shell: usermod --shell /bin/zsh {{ user }}

# - name: source .zshrc file
#   tags: alias,zsh
#   shell: bash -c 'source /home/{{ user }}/.zshrc 2> /dev/null'
# #  ignore_errors: true

# - name: source aliasrc file
#   tags: alias,zsh
#   shell: bash -c 'source /home/{{ user }}/aliasrc 2> /dev/null'

