---

- name: copy desktop background
  copy:
    src: files/joy-theme_1920x1080.svg
    dest: /usr/share/backgrounds/
    owner: "{{ user }}"
    group: "{{ user }}"
    backup: yes

- name: Ensure user config directories exist
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: '0755'
  loop:
    - /home/{{ user }}/.config/openbox
    - /home/{{ user }}/.config/tint2
    - /home/{{ user }}/.poshthemes

- name: install conky config
  tags: theme
  copy:
    src: files/conkyrc
    dest: /home/{{ user }}/.conkyrc
    owner: "{{ user }}"
    group: "{{ user }}"
    backup: yes

- name: install gmrun config
  copy:
    src: files/gmrunrc
    dest: /home/{{ user }}/.gmrunrc
    owner: "{{ user }}"
    group: "{{ user }}"
    backup: yes

- name: install autostart config
  copy:
    src: files/autostart
    dest: /home/{{ user }}/.config/openbox/
    owner: "{{ user }}"
    group: "{{ user }}"
    backup: yes

- name: Install OpenBox configurations
  copy:
    src: "files/{{ item }}"
    dest: "/home/{{ user }}/.config/openbox/{{ item }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: '0644'
    backup: yes
  loop:
    - autostart
    - menu.xml
    - rc.xml

- name: install lxdm config - autologin
  copy:
    src: files/cbpp.lxdm.conf
    dest: /etc/lxdm/
    owner: "root"
    group: "root"
    backup: yes

- name: install sources.list
  copy:
    src: files/sources.list
    dest: /etc/apt/
    owner: "root"
    group: "root"
    backup: yes

- name: unzip cairo-dock settings
  tags: cairo-dock
  unarchive:
    src: files/cairo-dock.tar.gz
    dest: /home/{{ user }}/.config/

- name: download tilix settings script
  tags: tilix,settings
  copy:
    src: files/tilix.sh
    dest: /home/{{ user }}
    mode: +x
    owner: "{{ user }}"
    group: "{{ user }}"

- name: Install PowerShell Oh My Posh themes
  copy:
    src: "{{ item }}"
    dest: "/home/{{ user }}/.poshthemes/{{ item | basename }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: '0644'
    backup: yes
  loop:
    - files/peru.omp.json
    - files/amro.omp.json
