- name: copy desktop background
  copy:
    src: files/joy-theme_1920x1080.svg
    dest: /usr/share/backgrounds/
    owner: "{{ user }}"
    group: "{{ user }}"
    backup: yes

- name: install conky config
  tags: theme
  copy:
    src: files/conkyrc
    dest: /home/{{ user }}/.conkyrc
    owner: "{{ user }}"
    group: "{{ user }}"
    backup: yes

- name: install gmrun config
  copy:
    src: files/gmrunrc
    dest: /home/{{ user }}/.gmrunrc
    owner: "{{ user }}"
    group: "{{ user }}"
    backup: yes

- name: install autostart config
  copy:
    src: files/autostart
    dest: /home/{{ user }}/.config/openbox/
    owner: "{{ user }}"
    group: "{{ user }}"
    backup: yes

- name: install menu config
  copy:
    src: files/menu.xml
    dest: /home/{{ user }}/.config/openbox/
    owner: "{{ user }}"
    group: "{{ user }}"
    backup: yes

- name: install rc config
  copy:
    src: files/rc.xml
    dest: /home/{{ user }}/.config/openbox/
    owner: "{{ user }}"
    group: "{{ user }}"
    backup: yes

- name: install tint2 config
  copy:
    src: files/tint2rc
    dest: /home/{{ user }}/.config/tint2/
    owner: "{{ user }}"
    group: "{{ user }}"
    backup: yes

- name: install sources.list
  copy:
    src: files/sources.list
    dest: /etc/apt/
    owner: "root"
    group: "root"
    backup: yes

- name: unzip cairo-dock settings
  tags: cairo-dock
  unarchive:
    src: files/cairo-dock.tar.gz
    dest: /home/{{ user }}/.config/

# - name: download Writer icon
#   copy:
#     src: files/LibreOffice_Writer.png
#     dest: /home/{{ user }}/.config/cairo-dock/current_theme/icons

- name: download tilix settings script
  tags: tilix,settings
  copy:
    src: files/tilix.sh
    dest: /home/{{ user }}
    mode: +x
    owner: "{{ user }}"
    group: "{{ user }}"

- name: install peru theme
  copy:
    src: files/peru.omp.json
    dest: /home/{{ user }}/.poshthemes/
    owner: "{{ user }}"
    group: "{{ user }}"
    backup: yes

