set bg=dark
set termguicolors

" Highlights searches
set hlsearch

" Searches incrementally
set incsearch

" Set tab size
set tabstop=4
set softtabstop=4
set shiftwidth=4

" Convert tab stops to spaces
set expandtab
set autoindent
set fileformat=unix

" Syntax highlighting
syntax on

" Line numbers
" set number relativenumber
set number

" Autocomplete
set wildmode=longest,list,full

" Replace all - alias S
nnoremap S :%s//g<Left><Left>

" Reload .vimrc config file
nnoremap <C-S-R> :source ~/.vimrc<CR>

" Remove highlighting
"nnoremap <C-H> :noh<CR>
map <silent> <leader><cr> :noh<cr>

" New tab - alias control-t
nnoremap <silent> <C-T> :tabnew<CR>

" Fast saving of a buffer
nmap <leader>w :w!<cr>

" Save and quit
nmap <C-s> :w<CR>
nmap <C-q> :q<CR>

" Fast save and quit
nmap <leader>q :wq<CR>

" Cycle tabs
nnoremap <C-Up> gT
nnoremap <C-Down> gt

" Toggle line numbers
nmap <leader>] :set number!<CR>                                                                                        

" Paste with system clipboard - alias control-i
nnoremap <S-Insert> <C-i>

" Switch to next buffer - alias control-n
nnoremap <silent> <C-N> :bn<CR>

" Switch to previous buffer - alias control-p
nnoremap <silent> <C-P> :bp<CR>

" Fast deleting of a buffer
nmap <leader>d :bd<CR>

" Use ctrl-arrow to select active split
nmap <silent> <C-S-up> :wincmd k<CR>
nmap <silent> <C-S-down> :wincmd j<CR>
nmap <silent> <C-S-left> :wincmd h<CR>
nmap <silent> <C-S-right> :wincmd l<CR>

" Line highlight in insert mode
:autocmd InsertEnter * set cursorline
:autocmd InsertLeave * set nocursorline

" Slim cursor in insert mode
let &t_SI = "\e[6 q"
let &t_EI = "\e[2 q"

set cursorline
hi cursorline cterm=none term=none
autocmd WinEnter * setlocal cursorline
autocmd WinLeave * setlocal nocursorline
highlight CursorLine guibg=#303000 ctermbg=234

