- name: create directories
  tags: directories,theme,icons
  file:
    path: /home/{{ user }}/{{item}}
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0755
  with_items:
      - ".poshthemes"
      - ".config/openbox"
