- name: install theme
  tags: theme
  unarchive:
    src: files/Flat-Dark.tar.gz
    dest: /usr/share/lxqt/themes

- name: install icons
  tags: icons
  unarchive:
    src: files/Emerald.tar.gz
    dest: /usr/share/icons

- name: back up rc.xml file
  tags: openbox
  copy:
    src: /home/{{user}}/.config/openbox/rc.xml
    dest: /home/{{user}}/.config/openbox/rc.xml.bak
  ignore_errors: true

- name: install rc.xml file
  tags: openbox
  copy:
    src: files/rc.xml
    dest: /home/{{ user }}/.config/openbox/rc.xml
    owner: "{{ user }}"
    group: "{{ user }}"


# - name: download cairo-dock config
#   tags: cairo-dock
#   unarchive:
#     src: files/cairo-dock.tar.gz
#     dest: /home/{{ user }}/.config
#     owner: "{{ user }}"
#     group: "{{ user }}"

# - name: download dock icons
#   tags: cairo-dock
#   copy:
#     src: files/notepadqq.svg
#     dest: /home/{{ user }}/.icons
#     owner: "{{ user }}"
#     group: "{{ user }}"

# - name: download dock icons
#   tags: cairo-dock
#   copy:
#     src: files/linux-tux-icon.png
#     dest: /home/{{ user }}/.icons
#     owner: "{{ user }}"
#     group: "{{ user }}"

