---

- block:
  - include_tasks: packages.yml
  - include_tasks: directories.yml
  - include_tasks: ../debian/tasks/oh-my-posh.yml
  - include_tasks: ../debian/tasks/zsh-alias.yml
  - include_tasks: ../debian/tasks/eza.yml
  - include_tasks: ../lubuntu/tasks/tilix_config.yml
  - include_tasks: ../debian/tasks/samba.yml
  - include_tasks: ../lubuntu/tasks/vscodium.yml
  - include_tasks: ../debian/tasks/cleanup.yml
  - include_tasks: ../base/tasks/fonts.yml
  - include_tasks: ../debian/tasks/fastfetch.yml
