- name: create directories
  tags: directories,theme,icons
  file:
    path: /home/{{ user }}/{{item}}
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0755
  with_items:
      - ".poshthemes"
      - ".config"
      - ".config/i3"
      - ".config/picom"
      - ".config/rofi"
      - ".config/onedrive"
      - "git"
      - ".config/QuiteRss"
      - ".ansible/tmp"
      - ".cache/dconf"
      - ".config/i3blocks"
      - "git/polybar"
      - "git/yay"
