- name: create directories
  tags: directories,theme,icons
  file:
    # become: "{{ user }}"
    path: /home/{{ user }}/{{item}}
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0755
  with_items:
      - ".poshthemes"
      - ".config"
      - ".config/i3"
      - ".config/picom"
      - ".config/rofi"
      - "git"
      - ".config/QuiteRss"

