- name: create safe git directory
  tags: git
  shell:
    cmd: git config --global --add safe.directory /home/{{ user }}/git
  args:
    executable: /bin/bash

- name: create safe git directory
  tags: git
  shell:
    cmd: git config --global --add safe.directory /home/{{ user }}/git/polybar
  args:
    executable: /bin/bash

- name: create safe git directory
  tags: git
  shell:
    cmd: git config --global --add safe.directory /home/{{ user }}/git/yay
  args:
    executable: /bin/bash

- name: create safe git directory
  tags: git
  shell:
    cmd: git config --global --add safe.directory /home/{{ user }}/.config/i3blocks
  args:
    executable: /bin/bash

- name: download polybar scripts
  tags: polybar
  git:
    repo: https://github.com/polybar/polybar-scripts.git
    dest: /home/{{ user }}/git/polybar
    clone: yes
    update: yes
    force: true

- name: download i3blocks-contrib scripts
  tags: i3blocks
  git:
    repo: https://github.com/vivien/i3blocks-contrib.git
    dest: /home/{{ user }}/.config/i3blocks
    clone: yes
    update: yes
    force: true

- name: download yay
  tags: yay
  git:
    repo: https://aur.archlinux.org/yay.git
    dest: /home/{{ user }}/git/yay
    clone: yes
    update: yes

# - name: install yay
#   become_user: "{{ user }}"
#   shell:
#     cmd: makepkg -$i
#     chdir: /home/{{ user }}/git/yay/
#   args:
#     executable: /bin/bash

- name: build and install yay
  command:
    chdir: /home/{{ user }}/git/yay
    cmd: "makepkg -sfi --noconfirm"
    creates: /usr/bin/yay