- name: back up lightdm.conf file
  tags: lightdm
  become: true
  copy:
    src: /etc/lightdm/lightdm.conf
    dest: /etc/lightdm/lightdm.conf.bak

- name: edit lightdm.conf file
  tags: lightdm
  become: true
  lineinfile:
    path: /etc/lightdm/lightdm.conf
    regexp: '^#display-setup-script='
    line: 'display-setup-script=xrandr --output Virtual-1 --mode 1920x1080'

# - name: enable lightdm
#   tags: lightdm
#   service:
#     name: lightdm
#     state: started
#     enabled: yes
