- name: install packages
  tags: base
  community.general.pacman:
    name: '{{item}}'
  loop:
      # Desktop environment
      - xorg
      - lightdm
      - lightdm-gtk-greeter
      - lightdm-gtk-greeter-settings
      - i3-wm
      - i3status
      - i3blocks
      - i3lock
      - picom
      - polybar

      # Base packages
      - linux-headers
      - dmenu
      - rofi
      - nano
      - base-devel
      - pacman-contrib
      - intel-ucode
      - virtualbox-guest-utils
      - go
      - sysstat
      - python-psutil

      # Terminal/Shell
      - zsh
      - zsh-syntax-highlighting
      - zsh-autosuggestions
      - tilix
      - ttf-nerd-fonts-symbols-2048-em
      - awesome-terminal-fonts
      - ttf-dejavu
      - otf-font-awesome
      - ttf-font-awesome

      # Utilities
      - htop
      - eza
      - ncdu
      - bat
      - duf
      - btop

      # Applications
      - firefox
      - thunderbird
      - pcmanfm
      - notepadqq
      - nitrogen
      - libreoffice-still
      - chromium
      - code
      - caja
      - vi
      - vim
      - discord
      - geany
      - ark
      - nomacs
      - dolphin

      # Services
      - xdg-utils
      - xdg-user-dirs
      - unzip
      - curl
      - wget
      - dconf
      - dconf-editor
      - samba
      - smbclient
      - cifs-utils
      - pulseaudio
      - pulseaudio-alsa
      - pavucontrol
      - alsa-utils
      - gnupg
      # - pipewire
      # - onedrive

      # Appearance
      - lxappearance
      - arc-icon-theme
      - breeze-icons
      # - arc-theme


  #  state: latest

# - name: setup script
#   tags: lightdm
#   copy:
#     src: files/script.sh
#     dest: /home/{{ user }}/
#     owner: "{{ user }}"
#     group: "{{ user }}"

# - name: set setup script to executable
#   tags: lightdm
#   file:
#     path: /home/{{ user }}/script.sh
#     mode: +x
