- name: download samba config file
  tags: samba
  get_url:
    url: https://raw.githubusercontent.com/zentyal/samba/master/examples/smb.conf.default
    dest: /etc/samba/smb.conf
    # clone: yes
    # update: yes
    # owner: root
    # group: root

- name: add samba share to config file
  tags: samba
  blockinfile:
    path: /etc/samba/smb.conf
    block: |
      [Downloads]
      comment = Downloads Share
      path = /home/{{ user }}/Downloads
      writeable = yes
      browsable = yes
      public = yes
      create mask = 0644
      force create mode = 0644
      directory mask = 0775
      force directory mode = 0775
      write list = user

- name: enable smb
  tags: samba
  service:
    name: smb
    state: reloaded
    enabled: yes
