- name: add hosts to /etc/hosts file
  tags: hosts
  blockinfile:
    path: /etc/hosts
    block: |
      127.0.0.1 localhost
      127.0.1.1 archlinuxvm

- name: enable timesyncd
  tags: timesyncd
  service:
    name: systemd-timesyncd
    state: started
    enabled: yes

- name: edit pacman config file
  tags: pacman
  lineinfile:
    path: /etc/pacman.conf
    regexp: '^#ParallelDownloads'
    line: 'ParallelDownloads = 5'
    backrefs: yes

- name: enable virtualbox
  tags: virtualbox
  service:
    name: vboxservice
    state: started
    enabled: yes

- name: back up poshtheme file
  tags: poshtheme
  copy:
    src: /home/{{ user }}/.poshthemes/quick-term.omp.json
    dest: /home/{{ user }}/.poshthemes/quick-term.omp.json.bak
    owner: "{{ user }}"
    group: "{{ user }}"

- name: install poshtheme config file
  tags: poshtheme
  copy:
    src: files/wopian.omp.json
    dest: /home/{{ user }}/.poshthemes
    owner: "{{ user }}"
    group: "{{ user }}"
    backup: yes

- name: Create home directories
  become_user: "{{ user }}"
  command:
    chdir: /home/{{ user }}
    cmd: "xdg-user-dirs-update"

- name: download qt5-webkit
  get_url:
    url: https://archive.archlinux.org/packages/q/qt5-webkit/qt5-webkit-5.212.0alpha4-18-x86_64.pkg.tar.zst
    dest: /home/{{ user }}

- name: install qt5-webkit
  pacman:
    name: /home/{{ user }}/qt5-webkit-5.212.0alpha4-18-x86_64.pkg.tar.zst
    state: present

- name: remove qt5-webkit file
  file:
    name: /home/{{ user }}/qt5-webkit-5.212.0alpha4-18-x86_64.pkg.tar.zst
    state: absent