- name: add hosts to /etc/hosts file
  tags: hosts
  blockinfile:
    path: /etc/hosts
    block: |
      127.0.0.1 localhost
      127.0.1.1 arch

- name: enable timesyncd
  tags: timesyncd
  service:
    name: systemd-timesyncd
    state: started
    enabled: yes

- name: edit pacman config file
  tags: pacman
  lineinfile:
    path: /etc/pacman.conf
    regexp: '^#ParallelDownloads'
    line: 'ParallelDownloads = 5'
    backrefs: yes

- name: enable virtualbox
  tags: virtualbox
  service:
    name: vboxservice
    state: started
    enabled: yes

- name: back up poshtheme file
  tags: poshtheme
  copy:
    src: /home/{{ user }}/.poshthemes/wopian.omp.json
    dest: /home/{{ user }}/.poshthemes/wopian.omp.json.bak
    owner: "{{ user }}"
    group: "{{ user }}"

- name: install poshtheme config file
  tags: poshtheme
  copy:
    src: files/wopian.omp.json
    dest: /home/{{ user }}/.poshthemes
    owner: "{{ user }}"
    group: "{{ user }}"
    backup: yes

# - name: install new zsh file
#   tags: poshtheme
#   copy:
#     src: files/zshrc
#     dest: /home/{{ user }}/.zshrc
#     owner: "{{ user }}"
#     group: "{{ user }}"
#     backup: yes

# - name: Run the equivalent of "pacman -Rdd", force remove package icu
#   pacman:
#     name: icu
#     state: absent
#     force: true

# - name: download qt5-webkit and icu-73
#   get_url:
#     url: https://archive.archlinux.org/packages/{{ item }}
#     dest: /home/{{ user }}
#     owner: "{{ user }}"
#     group: "{{ user }}"
#   with_items:
#     - q/qt5-webkit/qt5-webkit-5.212.0alpha4-18-x86_64.pkg.tar.zst
#     - i/icu/icu-73.2-2-x86_64.pkg.tar.zst

# - name: install qt5-webkit and icu-73
#   pacman:
#     name: /home/{{ user }}/{{ item }}
#     state: present
#   with_items:
#     - qt5-webkit-5.212.0alpha4-18-x86_64.pkg.tar.zst
#     - icu-73.2-2-x86_64.pkg.tar.zst

# - name: remove qt5-webkit and icu-73 files
#   file:
#     name: /home/{{ user }}/{{ item }}
#     state: absent
#   with_items:
#     - qt5-webkit-5.212.0alpha4-18-x86_64.pkg.tar.zst
#     - icu-73.2-2-x86_64.pkg.tar.zst

- name: install vim config file
  tags: vim
  copy:
    src: files/vimrc
    dest: /home/{{ user }}/.vimrc
    owner: "{{ user }}"
    group: "{{ user }}"
    backup: yes

- name: add extra Arch aliases - configs
  blockinfile:
    path: /home/{{ user }}/aliasrc
    insertafter: "alias zsrc='source ~/.zshrc'"
    marker: "## BEGIN ANSIBLE MANAGED BLOCK"
    block: |
      alias i3config='vim ~/.config/i3/config' # Quick access to the i3 config file
      alias polybar='vim ~/.config/polybar/config.ini'  # Quick access to polybar config file
      alias i3c='vim ~/.config/i3/config'
      alias pb='vim ~/.config/polybar/config.ini'

- name: add extra Arch aliases - package manager
  blockinfile:
    path: /home/{{ user }}/aliasrc
    insertafter: "alias pr='sudo pacman -R'"
    block: |
      alias yi='yay -S'
      alias ys='yay'
      alias pys='yay -Ss'
      alias yps='yay -Ss'
      alias yr='yay -R' 
      alias yu='yay -Sua'

- name: remove Ansible comment lines
  lineinfile:
    line: "{{ item }}"
    state: absent
    path: /home/{{ user }}/aliasrc
  with_items:
    - "# BEGIN ANSIBLE MANAGED BLOCK"
    - "# END ANSIBLE MANAGED BLOCK"
    - "## BEGIN ANSIBLE MANAGED BLOCK"
    - "## END ANSIBLE MANAGED BLOCK"



# - name: set wallpaper
#   tags: nitrogen
#   become_user: "{{ user }}"
#   command:
#     cmd: "nitrogen --set-auto --save /usr/share/wallpapers/arch.png"

# - name: download qt5-webkit
#   get_url:
#     url: https://archive.archlinux.org/packages/q/qt5-webkit/qt5-webkit-5.212.0alpha4-18-x86_64.pkg.tar.zst
#     dest: /home/{{ user }}
#     owner: "{{ user }}"
#     group: "{{ user }}"

# - name: install qt5-webkit
#   pacman:
#     name: /home/{{ user }}/qt5-webkit-5.212.0alpha4-18-x86_64.pkg.tar.zst
#     state: present

# - name: remove qt5-webkit file
#   file:
#     name: /home/{{ user }}/qt5-webkit-5.212.0alpha4-18-x86_64.pkg.tar.zst
#     state: absent


# - name: download icu-73
#   get_url:
#     url: https://archive.archlinux.org/packages/i/icu/icu-73.2-2-x86_64.pkg.tar.zst
#     dest: /home/{{ user }}
#     owner: "{{ user }}"
#     group: "{{ user }}"

# - name: install icu-73
#   pacman:
#     name: /home/{{ user }}/icu-73.2-2-x86_64.pkg.tar.zst
#     state: present

# - name: remove icu-73 file
#   file:
#     name: /home/{{ user }}/icu-73.2-2-x86_64.pkg.tar.zst
#     state: absent





# - name: back up vimrc file
#   tags: vimrc
#   become: true
#   copy:
#     src: /home/{{ user }}/.vimrc
#     dest: /home/{{ user }}/.vimrc.bak

# - name: edit vimrc file - lightline1
#   tags: vimrc
#   become: true
#   lineinfile:
#     path: /home/{{ user }}/.vimrc
#     regexp: '^let g:airline_theme'
#     line: "let g:lightline = {'colorscheme': 'powerline',}"

# - name: edit vimrc file - lightline2
#   tags: vimrc
#   become: true
#   lineinfile:
#     path: /home/{{ user }}/.vimrc
#     insertafter: "let g:lightline = {'colorscheme': 'powerline',}"
#     line: 'set laststatus=2'

# - name: edit vimrc file - airline1
#   tags: vimrc
#   become: true
#   lineinfile:
#     path: /home/{{ user }}/.vimrc
#     regexp: '^Plug 'vim-airline/vim-airline'
#     line: '" Plug 'vim-airline/vim-airline'

# - name: edit vimrc file - airline2
#   tags: vimrc
#   become: true
#   lineinfile:
#     path: /home/{{ user }}/.vimrc
#     regexp: '^Plug 'vim-airline/vim-airline-themes'
#     line: '" Plug 'vim-airline/vim-airline-themes'

