- name: add hosts to /etc/hosts file
  tags: hosts
  blockinfile:
    path: /etc/hosts
    block: |
      127.0.0.1 localhost
      127.0.1.1 arch

- name: enable timesyncd
  tags: timesyncd
  service:
    name: systemd-timesyncd
    state: started
    enabled: yes

- name: Configure pacman settings
  tags: pacman
  lineinfile:
    path: /etc/pacman.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backrefs: true
    backup: true
  loop:
    - { regexp: '^#ParallelDownloads', line: 'ParallelDownloads = 5' }
    - { regexp: '^#Color', line: 'Color' }
    - { regexp: '^#ILoveCandy', line: 'ILoveCandy' }
  notify: refresh pacman cache

- name: enable virtualbox
  tags: virtualbox
  service:
    name: vboxservice
    state: started
    enabled: yes
  when: ansible_virtualization_type == "virtualbox"

- name: back up poshtheme file
  tags: poshtheme
  copy:
    src: /home/{{ user }}/.poshthemes/wopian.omp.json
    dest: /home/{{ user }}/.poshthemes/wopian.omp.json.bak
    owner: "{{ user }}"
    group: "{{ user }}"

- name: Install configuration files
  tags: ["{{ item.tag }}"]
  copy:
    src: "files/{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "{{ item.mode | default('0644') }}"
    backup: true
  loop:
    - { src: "wopian.omp.json", dest: "/home/{{ user }}/.poshthemes/wopian.omp.json", tag: "poshtheme" }
    - { src: "gtksettings.ini", dest: "/home/{{ user }}/.config/gtk-3.0/settings.ini", tag: "gtk" }
    - { src: "vimrc", dest: "/home/{{ user }}/.vimrc", tag: "vim" }
    - { src: "OneDriveGUI.desktop", dest: "/home/{{ user }}/.local/share/applications/OneDriveGUI.desktop", tag: "onedrive", mode: "0755" }

- name: add extra Arch aliases - configs
  blockinfile:
    path: /home/{{ user }}/aliasrc
    insertafter: "alias zsrc='source ~/.zshrc'"
    marker: "## BEGIN ANSIBLE MANAGED BLOCK"
    block: |
      alias i3config='vim ~/.config/i3/config' # Quick access to the i3 config file
      alias polybar='vim ~/.config/polybar/config.ini'  # Quick access to polybar config file
      alias i3c='vim ~/.config/i3/config'
      alias pb='vim ~/.config/polybar/config.ini'

- name: add extra Arch aliases - package manager
  blockinfile:
    path: /home/{{ user }}/aliasrc
    insertafter: "alias pr='sudo pacman -R'"
    block: |
      alias yi='yay -S'
      alias ys='yay'
      alias pys='yay -Ss'
      alias yps='yay -Ss'
      alias yr='yay -R' 
      alias yu='yay -Sua'

- name: remove Ansible comment lines
  lineinfile:
    line: "{{ item }}"
    state: absent
    path: /home/{{ user }}/aliasrc
  with_items:
    - "# BEGIN ANSIBLE MANAGED BLOCK"
    - "# END ANSIBLE MANAGED BLOCK"
    - "## BEGIN ANSIBLE MANAGED BLOCK"
    - "## END ANSIBLE MANAGED BLOCK"
