---

- name: set wallpaper
  tags: nitrogen
  become_user: "{{ user }}"
  command:
    # chdir: /
    cmd: "nitrogen /usr/share/wallpapers/arch.png"

- name: download qt5-webkit
  pacman:
    name: https://archive.archlinux.org/packages/q/qt5-webkit/qt5-webkit-5.212.0alpha4-18-x86_64.pkg.tar.zst
    extra_args: -U