---

- name: add user group
  group:
    name: "{{ user }}"
    state: present

- name: add user to system
  user:
    name: "{{ user }}"
    groups: wheel,{{ user }}
    append: true
    shell: /bin/bash
    create_home: true
    password: "{{ userpass | password_hash('sha512') }}"
    generate_ssh_key: true
    ssh_key_file: /home/{{ user }}/.ssh/id_ed25519
    ssh_key_comment: "arch linux"
    ssh_key_type: ed25519
    update_password: on_create

- name: allow wheel sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^#%wheel ALL=(ALL:ALL) ALL'
    line: '%wheel ALL=(ALL) ALL'
    validate: 'visudo -cf %s'
