firefox_package: firefox
libreoffice_package: libreoffice
chromium_package: chromium
ssh_package: openssh
user: matt
fd_package: fd-find
init_status: systemctl status
init_start: systemctl start
init_restart: systemctl restart
bat: bat
pkgmgr_install: dnf install
pkgmgr_search: dnf search
pkgmgr_upgrade: dnf upgrade
pkgmgr_remove: dnf remove
pkgmgr_info: dnf info
pkgmgr_install_short: di
pkgmgr_search_short: ds
pkgmgr_upgrade_short: du
pkgmgr_remove_short: dr
airline_theme: cobalt2
vim_theme: iceberg
omp_theme: powerlevel10k_rainbow
copyq: copyq
alias_template_file: alias.j2
zshrc_template_file: zshrc.j2
vimrc_template_file: vimrc.j2
fetch: fastfetch --load-config examples/10.jsonc