---

- name: install icewm configs
  copy:
    src: files/{{ item }}
    dest: /home/{{ user }}/.icewm/
    owner: "{{ user }}"
    group: "{{ user }}"
    backup: yes
  with_items:
    - menu
    - startup
    - theme
    - preferences
    - prefoverride
    - toolbar
    - keys

- name: install icewm menu-applications
  copy:
    src: files/menu-applications
    dest: /usr/share/desktop-menu/.icewm/
    owner: "root"
    group: "{{ user }}"
    backup: yes

- name: install wallpaper
  copy:
    src: files/debian.jpg
    dest: /usr/share/wallpaper/debian.jpg
    owner: "root"
    group: "root"

- name: install Araita-Dark theme
  tags: theme
  unarchive:
    src: files/Araita-Dark.tar.gz
    dest: /usr/share/icewm/themes/
    owner: "root"
    group: "root"

- name: install modified icewm theme file
  copy:
    src: files/default.theme
    dest: /usr/share/icewm/themes/Araita-Dark+/default.theme
    owner: "root"
    group: "root"

- name: edit vimrc file - theme
  tags: vimrc
  become: true
  lineinfile:
    path: /home/{{ user }}/.vimrc
    regexp: '^colorscheme'
    line: "colorscheme onedark"

- name: edit vimrc file - airline
  tags: vimrc
  become: true
  lineinfile:
    path: /home/{{ user }}/.vimrc
    regexp: '^let g:airline_theme'
    line: "let g:airline_theme='light'"

- name: install vim themes - 1
  copy:
    src: files/onedark-autoload.vim
    dest: /home/{{ user }}/.vim/autoload/onedark.vim
    owner: "{{ user }}"
    group: "{{ user }}"

- name: install vim themes - 2
  copy:
    src: files/onedark-colors.vim
    dest: /home/{{ user }}/.vim/colors/onedark.vim
    owner: "{{ user }}"
    group: "{{ user }}"

- name: install compton config
  copy:
    src: files/compton.conf
    dest: /home/{{ user }}/.config/
    owner: "{{ user }}"
    group: "{{ user }}"

- name: edit desktop-session
  lineinfile:
    path: /home/{{ user }}/.desktop-session/default-desktop
    regexp: '(.*?)'
    line: "icewm"

- name: edit fehbg
  lineinfile:
    path: /home/{{ user }}/.fehbg
    regexp: '^feh'
    line: "feh --no-fehbg --bg-scale '/usr/share/wallpaper/debian.jpg'"

- name: install conky config file
  tags: conky
  copy:
    src: files/conkyrc
    dest: /home/{{ user }}/.conkyrc
    backup: yes
    owner: "{{ user }}"
    group: "{{ user }}"

- name: install conkywonky
  tags: conky
  copy:
    src: files/conkywonky
    dest: /usr/bin/
    backup: yes
    mode: +x
    owner: "root"
    group: "root"

- name: install gtk3 config file
  tags: gtk
  copy:
    src: files/settings.ini
    dest: /home/{{ user }}/.config/gtk-3.0/
    backup: yes
    owner: "{{ user }}"
    group: "{{ user }}"

- name: download Teams AppImage
  get_url: 
    url: https://github.com/IsmaelMartinez/teams-for-linux/releases/download/v1.3.23/teams-for-linux-1.3.23.AppImage
    dest: /home/{{ user }}/Downloads/
    mode: +x
    owner: "{{ user }}"
    group: "{{ user }}"

- name: extract anyconnect archive
  unarchive:
    src: files/anyconnect-linux64-4.10.07073.tar.gz
    dest: /home/{{ user }}/Downloads/anyconnect/
    owner: "{{ user }}"
    group: "{{ user }}"
    create: yes

- name: install firefox.desktop file
  copy:
    src: files/firefox.desktop
    dest: /usr/share/applications/firefox.desktop
    owner: "root"
    group: "root"


# - name: install menu icon
#   copy:
#     src: files/menu-bar.png
#     dest: /usr/share/icons/
#     owner: root
#     group: root

# - name: download tilix settings script
#   tags: tilix,settings
#   copy:
#     src: files/tilix.sh
#     dest: /home/{{ user }}
#     mode: +x
#     owner: "{{ user }}"
#     group: "{{ user }}"

# - name: install sources.list
#   copy:
#     src: files/sources.list
#     dest: /etc/apt/
#     owner: "root"
#     group: "root"
#     backup: yes

# - name: install jwm configs
#   copy:
#     src: files/{{ item }}
#     dest: /home/{{ user }}/.jwm/
#     owner: "{{ user }}"
#     group: "{{ user }}"
#     backup: yes
#   with_items:
#     - menu
#     - startup
#     - theme
#     - tray

# - name: install jwmrc config
#   copy:
#     src: files/jwmrc
#     dest: /home/{{ user }}/.jwmrc
#     owner: "{{ user }}"
#     group: "{{ user }}"
#     backup: yes

