---

- name: install sources.list
  copy:
    src: files/sources.list
    dest: /etc/apt/
    owner: "root"
    group: "root"
    backup: yes

- name: install jwm configs
  copy:
    src: files/{{ item }}
    dest: /home/{{ user }}/.jwm/
    owner: "{{ user }}"
    group: "{{ user }}"
    backup: yes
  with_items:
    - menu
    - startup
    - theme
    - tray

- name: install jwmrc config
  copy:
    src: files/jwmrc
    dest: /home/{{ user }}/.jwmrc
    owner: "{{ user }}"
    group: "{{ user }}"
    backup: yes

- name: edit vimrc file - theme
  tags: vimrc
  become: true
  lineinfile:
    path: /home/{{ user }}/.vimrc
    regexp: '^colorscheme'
    line: "colorscheme onedark"

- name: edit vimrc file - airline
  tags: vimrc
  become: true
  lineinfile:
    path: /home/{{ user }}/.vimrc
    regexp: '^let g:airline_theme'
    line: "let g:airline_theme='light'"

- name: install vim themes
  copy:
    src: files/onedark-autoload.vim
    dest: /home/{{ user }}/.vim/autoload/onedark.vim
    owner: "{{ user }}"
    group: "{{ user }}"

- name: install vim themes
  copy:
    src: files/onedark-colors.vim
    dest: /home/{{ user }}/.vim/colors/onedark.vim
    owner: "{{ user }}"
    group: "{{ user }}"

- name: download tilix settings script
  tags: tilix,settings
  copy:
    src: files/tilix.sh
    dest: /home/{{ user }}
    mode: +x
    owner: "{{ user }}"
    group: "{{ user }}"
