---

- name: install icewm configs
  copy:
    src: files/{{ item }}
    dest: /home/{{ user }}/.icewm/
    owner: "{{ user }}"
    group: "{{ user }}"
    backup: yes
  with_items:
    - menu
    - startup
    - theme
    - preferences
    - prefoverride
    - toolbar
    - keys

- name: install icewm menu-applications
  copy:
    src: files/menu-applications
    dest: /usr/share/desktop-menu/.icewm/
    owner: "root"
    group: "{{ user }}"
    backup: yes

- name: install wallpaper
  copy:
    src: files/debian.jpg
    dest: /usr/share/wallpaper/debian.jpg
    owner: "root"
    group: "root"

- name: set wallpaper
  tags: nitrogen
  become_user: "{{ user }}"
  command:
    cmd: "nitrogen --set-auto --save /usr/share/wallpaper/debian.jpg"
  ignore_errors: true

- name: install Araita-Dark theme
  tags: theme
  unarchive:
    src: files/Araita-Dark.tar.gz
    dest: /usr/share/icewm/themes/
    owner: "root"
    group: "root"

- name: install modified icewm theme file
  copy:
    src: files/default.theme
    dest: /usr/share/icewm/themes/Araita-Dark+/default.theme
    owner: "root"
    group: "root"

- name: edit vimrc file - theme
  tags: vimrc
  become: true
  lineinfile:
    path: /home/{{ user }}/.vimrc
    regexp: '^colorscheme'
    line: "colorscheme onedark"

- name: edit vimrc file - airline
  tags: vimrc
  become: true
  lineinfile:
    path: /home/{{ user }}/.vimrc
    regexp: '^let g:airline_theme'
    line: "let g:airline_theme='light'"

- name: install vim onedark theme files
  tags: [vimrc, theme]
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: '0644'
  loop:
    - { src: "files/onedark-autoload.vim", dest: "/home/{{ user }}/.vim/autoload/onedark.vim" }
    - { src: "files/onedark-colors.vim", dest: "/home/{{ user }}/.vim/colors/onedark.vim" }

- name: install compton config
  copy:
    src: files/compton.conf
    dest: /home/{{ user }}/.config/
    owner: "{{ user }}"
    group: "{{ user }}"

- name: edit desktop-session
  lineinfile:
    path: /home/{{ user }}/.desktop-session/default-desktop
    regexp: 'zzz-icewm'
    line: "icewm"

- name: edit fehbg
  lineinfile:
    path: /home/{{ user }}/.fehbg
    regexp: '^feh'
    line: "feh --no-fehbg --bg-scale '/usr/share/wallpaper/debian.jpg'"

- name: install conky configuration
  tags: conky
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    backup: yes
  loop:
    - { src: "files/conkyrc", dest: "/home/{{ user }}/.conkyrc", owner: "{{ user }}", group: "{{ user }}", mode: "0644" }
    - { src: "files/conkywonky", dest: "/usr/bin/conkywonky", owner: "root", group: "root", mode: "0755" }

- name: install gtk3 config file
  tags: gtk
  copy:
    src: files/settings.ini
    dest: /home/{{ user }}/.config/gtk-3.0/
    backup: yes
    owner: "{{ user }}"
    group: "{{ user }}"

- name: download Teams AppImage
  get_url: 
    url: https://github.com/IsmaelMartinez/teams-for-linux/releases/download/v2.3.0/teams-for-linux-2.3.0.AppImage
    dest: /home/{{ user }}/Downloads/
    mode: +x
    owner: "{{ user }}"
    group: "{{ user }}"

- name: extract anyconnect archive
  unarchive:
    src: files/anyconnect-linux64-4.10.07073.tar.gz
    dest: /home/{{ user }}/Downloads
    owner: "{{ user }}"
    group: "{{ user }}"
    # creates: yes

- name: install desktop files and icons
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode | default('0644') }}"
  loop:
    - { src: "files/firefox.desktop", dest: "/usr/share/applications/firefox.desktop", owner: "root", group: "root" }
    - { src: "files/Microsoft_Office_Teams.svg", dest: "/home/{{ user }}/.local/share/icons/Microsoft_Office_Teams.svg", owner: "{{ user }}", group: "{{ user }}" }
