---

- name: download tilix conf file
  tags: tilix
  copy:
    src: files/tilix.dconf
    dest: /home/{{ user }}/
    owner: "{{ user }}"
    group: "{{ user }}"
    
# - name: tilix settings
#   become_user: "{{ user }}"
#   shell:
#     cmd: dconf load /com/gexperts/Tilix/ < tilix.dconf
#     chdir: /home/{{ user }}
#   args:
#     executable: /bin/bash

- name: load tilix dconf settings
  tags: tilix
  become: true
  become_user: "{{ user }}"
  shell: |
    export DISPLAY=${DISPLAY:-:0}
    dconf load /com/gexperts/Tilix/ < ~/.config/tilix.dconf
  args:
    executable: /bin/bash
