---

- name: check if oh-my-zsh directory exists
  tags: oh-my-zsh
  stat:
    path: /home/{{ user }}/.oh-my-zsh
  register: omz

- name: Download oh-my-zsh
  tags: zsh
  get_url:
    url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: /home/{{ user }}
    mode: +x
    owner: "{{ user }}"
    group: "{{ user }}"

- name: Install oh-my-zsh
  become_user: "{{ user }}"
  shell:
    cmd: ./install.sh
    chdir: /home/{{ user }}
  args:
    executable: /bin/bash
  when: omz.stat.exists == false

- name: create safe git directory
  tags: git
  shell:
    cmd: git config --global --add safe.directory /home/{{ user }}/.oh-my-zsh/custom/themes/powerlevel10k
  args:
    executable: /bin/bash

- name: download powerlevel10k theme
  tags: zsh
  git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: /home/{{ user }}/.oh-my-zsh/custom/themes/powerlevel10k/
    clone: yes
    update: yes
    force: true

- name: install zsh configuration files
  tags: [zsh, config]
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: '0644'
    backup: yes
  loop:
    - { src: "files/zshrc", dest: "/home/{{ user }}/.zshrc" }
    - { src: "files/p10k.zsh", dest: "/home/{{ user }}/.p10k.zsh" }

- name: change shell
  tags: zsh,shell
  shell: usermod --shell /bin/zsh {{ user }}
