# - name: back up existing conky config file
#   tags: conky
#   command: mv /etc/conky/conky.conf /etc/conky/conky.conf.bak

- name: create conky directory
  tags: conky
  file:
    path: /etc/conky
    state: directory
    mode: 0755
    owner: root
    group: root


- name: download new conky config file
  tags: conky
  copy:
    src: files/conky.conf
    dest: /etc/conky/conky.conf
    backup: yes
    owner: root
    group: root
