- name: create font directory
  tags: font
  file:
    path: /home/{{ user }}/.local/share/fonts
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0755

- name: install fonts
  tags: font,fonts
  unarchive:
    src: files/fonts.tar.gz
    dest: /home/{{ user }}/.local/share/fonts
    owner: "{{ user }}"
    group: "{{ user }}"

- name: install fonts - Inconsolata
  tags: font,fonts
  unarchive:
    src: files/Inconsolata.zip
    dest: /home/{{ user }}/.local/share/fonts
    owner: "{{ user }}"
    group: "{{ user }}"

- name: reload font cache
  tags: font
  shell: fc-cache -f -v > /dev/null
