---

- name: install fzf keybindings
  copy:
    src: files/key-bindings.zsh
    dest: /usr/share/fzf/
    owner: "root"
    group: "root"
    backup: yes

- name: download fzf completions
  get_url:
    url: https://raw.githubusercontent.com/junegunn/fzf/master/shell/completion.zsh
    dest: /usr/share/fzf/
    owner: "root"
    group: "root"
    backup: yes
