# Load distribution-specific variables
- name: Load distribution-specific variables
  include_vars: "{{ ansible_distribution }}.yml"

- name: Execute main configuration tasks
  block:
    - name: Arch Linux specific tasks
      include_tasks: "{{ item }}"
      loop:
        - ../arch/tasks/packages.yml
        - ../arch/tasks/users.yml
      when: ansible_distribution == "Archlinux"

    - name: Void Linux specific tasks
      include_tasks: "{{ item }}"
      loop:
        - ../void/tasks/packages.yml
        - ../void/tasks/users.yml
      when: ansible_distribution == "Void"

    - name: create directories
      include_tasks: directories.yml
    
    # - name: install general packages
    #   include_tasks: packages.yml
    #   when: ansible_distribution != "Void"
    
    - name: apply config files
      include_tasks: configs.yml

    - name: configure applications
      include_tasks: "{{ item }}"
      loop:
        - geany.yml
        - conky.yml
        - fonts.yml
        - vim.yml
        - fzf.yml

    - name: Configure OneDrive GUI
      include_tasks: tasks/onedrivegui.yml
      when: ansible_distribution != "Archlinux"
