- include_vars: "{{ ansible_distribution }}.yml"

- block:
  - include_tasks: ../arch/tasks/packages.yml
    when: ansible_distribution == "Archlinux"
  - include_tasks: ../arch/tasks/users.yml
    when: ansible_distribution == "Archlinux"
  - include_tasks: ../void/tasks/packages.yml
    when: ansible_distribution == "Void"
  - include_tasks: ../void/tasks/users.yml
    when: ansible_distribution == "Void"
  - include_tasks: directories.yml
  - include_tasks: tasks/packages.yml
    # when: ansible_distribution != "Void"
  - include_tasks: configs.yml
  - include_tasks: tasks/geany.yml
  - include_tasks: tasks/conky.yml
  - include_tasks: tasks/fonts.yml
  - include_tasks: tasks/onedrivegui.yml   ## Can't use with Arch
    when: ansible_distribution != "Archlinux"
  - include_tasks: tasks/nano.yml
  - include_tasks: fzf.yml

    # - include_tasks: tasks/directories.yml
# - include_tasks: tasks/notepadqq_dependencies.yml
  # - include_tasks: tasks/pidgin_dependencies.yml
  # - include_tasks: tasks/google_chat.yml
  # - include_tasks: tasks/notepadqq.yml
  # - include_tasks: tasks/sshd.yml
