- name: create nanorc directory
  tags: nano
  file:
    path: /home/{{ user }}/nanorc
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0755

- name: install nanorc files
  tags: font,fonts
  unarchive:
    src: files/nanorc.tar.gz
    dest: /home/{{ user }}
    owner: "{{ user }}"
    group: "{{ user }}"

- name: nano config file
  tags: nano
  copy:
    src: files/nanorc
    dest: /home/{{ user }}/.nanorc
    owner: "{{ user }}"
    group: "{{ user }}"

- name: vim config file
  tags: vim
  copy:
    src: files/vimrc
    dest: /home/{{ user }}/.vimrc
    owner: "{{ user }}"
    group: "{{ user }}"

- name: create vim directories
  tags: vim
  file:
    path: /home/{{ user }}/.vim/{{ item }}
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0755
  with_items:
    - colors
    - plugged
    - autoload

- name: copy vim-plug file
  tags: vim
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: /home/{{ user }}/.vim/autoload/
    owner: "{{ user }}"
    group: "{{ user }}"


- name: copy vim theme files
  tags: vim
  file:
    src: files/{{ item }}
    dest: /home/{{ user }}/.vim/colors/
    owner: "{{ user }}"
    group: "{{ user }}"
  with_items:
    - solarized8_high.vim
    - iceberg.vim
    - two-firewatch.vim

- name: tmux config file
  tags: tmux
  copy:
    src: files/tmux.conf
    dest: /home/{{ user }}/.tmux.conf
    owner: "{{ user }}"
    group: "{{ user }}"