- name: install notepadqq dependencies
  tags: notepadqq,dependencies
  package:
    name:
      - qt5-qtbase-devel
      - qt5-qttools-devel
      - qt5-qtwebengine-devel
      - qt5-qtwebsockets-devel
      - qt5-qtsvg-devel
      - uchardet
      - uchardet-devel
      - qt5-qtwebchannel-devel
      - pkgconfig
    when: ansible_distribution == "Fedora"

- name: install notepadqq dependencies - Debian
  tags: notepadqq,dependencies,debian
  apt:
    name:
      - libqt5websockets5
      - libqt5websockets5-dev
      - qtwebengine5-dev
      - qtwebengine5-dev-tools
      - libqt5svg5
      - libqt5svg5-dev
      - coreutils
      - libuchardet-dev
      - libuchardet0
      - pkg-config
      - qttools5-dev
      - qttools5-dev-tools
#    state: latest
#  when: ansible_distribution == "Debian"
