- name: install packages
  tags: base
  package:
    name:
      - zsh
      - zsh-syntax-highlighting
      - zsh-autosuggestions
      - tilix
      - htop
      - conky
      - exa
      - ncdu
      - bat
      - onedrive
      - samba
      - cifs-utils
      - "{{ firefox_package }}"
      - thunderbird
      - "{{ libreoffice_package }}"
      - gnupg
      - geany
      - unzip
      - bat
      - dconf-editor
      - "{{ chromium_package }}"
      - "{{ ssh_package }}"
      - btop
    state: latest

- name: install debian specific packages
  tags: debian,base
  apt:
    name:
      - plank
      - dconf-cli
      - python3-psutil
      - smbclient
    state: latest
  when: ansible_distribution == "Debian"

- name: System | Repositories | Add RPM Fusion GPG keys
  tags: system,repository,rpmfusion
  ansible.builtin.rpm_key:
    key: "{{ items }}"
    state: present
  with_items:
    - {{ rpmfusion_free_gpg_key }}
    - {{ rpmfusion_nonfree_gpg_key  }}
  when: ansible_distribution == 'Fedora'

 - name: System | Repositories | Add RPM Fusion GPG keys
  tags: system,repository,rpmfusion
  ansible.builtin.rpm_key:
    key: "{{ items }}"
    state: present
  with_items:
    - {{ rpmfusion_free_repository  }}
    - {{ rpmfusion_nonfree_repository }}
  when: ansible_distribution == 'Fedora'
     
- name: install fedora specific packages
  tags: fedora,base
  dnf: 
    name:
      - cairo-dock
      - duf
      - discord
      - copyq
      - deadbeef
      - deadbeef-plugins
      - audacious
    state: latest
  when: ansible_distribution == "Fedora"

- name: install Lubuntu specific packages
  tags: lubuntu,base
  apt:
    name:
      - dconf-cli
      - cairo-dock
      - duf
    state: latest
  when: flavor.stdout == "Lubuntu"

- name: install openh264
  tags: fedora,base,openh264
  dnf:
    name:
      - gstreamer1-plugin-openh264
      - mozilla-openh264
    enablerepo: fedora-cisco-openh264
    state: present
  when: ansible_distribution == "Fedora"

- name: install Void and Arch packages
  tags: void,arch
  package:
    name:
      - arc-icon-theme
      - curl
      - dconf
      - dconf-editor
      - dmenu
      - duf
      - "{{ i3_package }}"
      - i3lock
      - i3status
      - lightdm
      - "{{ lightdm-gtk-greeter_package }}"
      - lightdm-gtk-greeter-settings
      - linux-headers
      - lxappearance
      - nano
      - nitrogen
      - notepadqq
      - pcmanfm
      - picom
      - polybar
      - pulseaudio
      - rofi
      - smbclient
      - unzip
      - wget
      - xdg-user-dirs
      - xdg-utils
      - xorg
  when: ansible_distribution in ["Archlinux", "Void"]

- name: install Arch packages
  tags: Arch
  pacman:
    name:
      - alsa-utils
      - awesome-terminal-fonts
      - base-devel
      - caja
      - code
      - discord
      - go
      - intel-ucode
      - otf-font-awesome
      - pacman-contrib
      - pavucontrol
      - pulseaudio-alsa
      - python-psutil
      - sysstat
      - ttf-dejavu
      - ttf-font-awesome
      - ttf-nerd-fonts-symbols-2048-em
      - vi
      - vim
      - virtualbox-guest-utils
  when: ansible_distribution == "Archlinux"

- name: install Void packages
  tags: Void
  community.general.xbps:
    name:
      - arc-theme
      - dbus
      - nerd-fonts
      - quiterss
  when: ansible_distribution == "Void"
