- name: install packages
  tags: base
  package:
    name:
      - zsh
      - zsh-syntax-highlighting
      - zsh-autosuggestions
      - tilix
      - htop
      - conky
      - ncdu
      - bat
      # - onedrive  ## Not available on Arch
      - samba
      - cifs-utils
      - "{{ firefox_package }}"
      - thunderbird
      - "{{ libreoffice_package }}"
      - gnupg
      - geany
      - unzip
      - dconf-editor
      - "{{ chromium_package }}"
      - "{{ ssh_package }}"
      - btop
      - "{{ copyq }}"
      - "{{ fd_package }}"
      - fzf
      - ripgrep
      - duf
      - vim
      # - eza
      # - fastfetch
      - rsync
<<<<<<< HEAD
      - syncthing
=======
      - flameshot
>>>>>>> 9e38e70 (adding dunst and flameshot to arch&base packages)
    state: latest

