- name: install packages
  tags: base
  package:
    name:
      - zsh
      - zsh-syntax-highlighting
      - zsh-autosuggestions
      - tilix
      - pidgin
      - htop
      - conky
      - exa
      - ncdu
      - bat
      - onedrive
      - python3-pip
      - samba
      - cifs-utils
    state: latest

- name: install debian specific packages
  tags: debian,base
  apt:
    name:
      - plank
      - dconf-editor
      - dconf-cli
      - python3-psutil
      - smbclient
    state: latest
  when: ansible_distribution == "Debian"

- name: install fedora specific packages
  tags: fedora,base
  dnf: 
    name:
      - cairo-dock
      - duf
    state: latest
  when: ansible_distribution == "Fedora"

- name: install Lubuntu specific packages
  tags: lubuntu,base
  apt:
    name:
      - dconf-editor
      - dconf-cli
      - python3-psutil
      - smbclient
      - cairo-dock
      - duf
      - ssh
    state: latest
  when: flavor == "Lubuntu"

- name: install openh264
  tags: fedora,base,openh264
  dnf:
    name:
      - gstreamer1-plugin-openh264
      - mozilla-openh264
    enablerepo: fedora-cisco-openh264
    state: present
  when: ansible_distribution == "Fedora"
