- name: install packages
  tags: base
  package:
    name:
      - zsh
      - zsh-syntax-highlighting
      - zsh-autosuggestions
      - tilix
      - htop
      - conky
      - ncdu
      - bat
      - onedrive
      - samba
      - cifs-utils
      - "{{ firefox_package }}"
      - thunderbird
      - "{{ libreoffice_package }}"
      - gnupg
      - geany
      - unzip
      - dconf-editor
      - "{{ chromium_package }}"
      - "{{ ssh_package }}"
      - btop
      - copyq
      - "{{ fd_package }}"
      - fzf
      - ripgrep
      - duf
      - vim
      - smbclient
    state: latest

