- name: install pidgin dependencies
  tags: pidgin,dependencies
  package:
    name:
      - json-glib-devel
      - libpurple-devel
      - glib2-devel
      - libpurple-devel
      - protobuf-c-devel
      - protobuf-c-compiler
