---

- name: copy vim-plug file
  tags: vim
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: /home/{{ user }}/.vim/autoload/
    owner: "{{ user }}"
    group: "{{ user }}"

- name: copy vim theme files
  tags: vim
  copy:
    src: files/{{ item }}
    dest: /home/{{ user }}/.vim/colors/
    owner: "{{ user }}"
    group: "{{ user }}"
  with_items:
    - "solarized8_high.vim"
    - "iceberg.vim"
    - "two-firewatch.vim"
    - "gotham.vim"

- name: tmux config file
  tags: tmux
  copy:
    src: files/tmux.conf
    dest: /home/{{ user }}/.tmux.conf
    owner: "{{ user }}"
    group: "{{ user }}"