---
# - name: get kernel version
#   tasks:
#     - shell:
#         cmd: uname -r
#       register: uname
#       args:
#         executable: /bin/bash
#     - debug:
#         msg={{uname.stdout}}

- name: collect uname
  tags: virtualbox
  shell: uname -r
  register: uname

- name: install packages
  apt:
    name:
      - puppetserver
      - samba
      - cifs-utils
      - tilix
      - htop
      - bat
      - ncdu

      # VirtualBox
      - build-essential
      - linux-headers-generic
      - linux-headers-{{ uname.stdout }}
      - dkms
      - virtualbox-guest-x11
      - virtualbox-guest-dkms
      - virtualbox-guest-utils

      # i3
      - xorg
      - i3

    

