---
- name: collect uname
  tags: virtualbox
  shell: uname -r
  register: uname

- name: install packages
  apt:
    name:
      - puppetserver
      - python3-psutil
      - dconf-cli

      # VirtualBox
      - build-essential
      - linux-headers-generic
      - linux-headers-{{ uname.stdout }}
      - dkms
      - virtualbox-guest-x11
      - virtualbox-guest-dkms
      - virtualbox-guest-utils

      # i3
      - xorg
      - i3

    

